// This file was autogenerated by /Users/voss/project/s3/js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/Users/voss/project/jvjsdoc/search.js', ['jvjsdoc'], ['goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventType', 'goog.ui.AutoComplete.Basic', 'goog.ui.AutoComplete.EventType']);
